import "@/assets/styles/globals.css";
import Header from "@/components/header";
import { TLang } from "@/types";
import type { Metadata } from "next";
import { Abril_Fatface, Roboto } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  display: "swap",
});

const abrilFatface = Abril_Fatface({
  subsets: ["latin"],
  variable: "--font-abril-fatface",
  display: "swap",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout(props: {
  children: React.ReactNode;
  params: Promise<{ lang: TLang }>;
}) {
  const { children } = props;
  const params = await props.params;
  const { lang } = params;

  return (
    <html lang={lang} className={`${roboto.variable} ${abrilFatface.variable}`}>
      <Header />
      <body>{children}</body>
    </html>
  );
}

export async function generateStaticParams() {
  return [{ lang: "it" }, { lang: "en" }];
}
